#!/bin/bash
WATER_DEC=$(echo "$WATER" | tr 'water' '01234' | awk '{s=0; for (i=1; i<=length($0); i++) s=s*5+substr($0,i,1); print s}')
STIR_DEC=$(echo "$STIR" | tr 'stir.' '01234' | awk '{s=0; for (i=1; i<=length($0); i++) s=s*5+substr($0,i,1); print s}'); RESULT=$(echo $((WATER_DEC+STIR_DEC)) | awk '{n=$1; s=""; while (n > 0) {s=sprintf("%c", 98+n%7) s; n=int(n/7)} print s}'); echo "$RESULT"

